console.log(`===========================================`)
// console.log(`=========== GREETING ======================`)
// console.log(``)
// console.log(`===========================================`)
// console.log(`=========== CAPITALIZE ====================`)
// console.log(`===========================================`)
// console.log(`INPUT: fooBar  |   EXPECTED: Foobar  |   OUTPUT: ${capitalize("fooBar")} `)
// console.log(`INPUT: nodeJs  |   EXPECTED: Nodejs  |   OUTPUT: ${capitalize("nodeJs")} `)
// console.log(``)
// console.log(`===========================================`)
// console.log(`=========== CAPITALIZED COLORS ============`) // HAD TO MOVE OUTCOMES TO THE NEXT LINE BECAUSE THEY WOULDN'T
// console.log(`===========================================`) // DISPLAY PROPERLY USING STRING CONCATENATION
// console.log(`INPUT: ["red", "blue", "green"]  |  EXPECTED: ['Red', 'Blue', 'Green']  |  OUTPUT:`)
// console.log(capitalizeMap(["red", "blue", "green"]))
// console.log(`INPUT: ["yeLLOw", "oRaNgE", "bLACK"]  |  EXPECTED: ['Yellow, 'Orange', 'Black']  |  OUTPUT:`)
// console.log(capitalizeMap(["yeLLOw", "oRaNgE", "bLACK"]))  
// console.log(``)
// console.log(`===========================================`)
// console.log(`=========== FILTER LESS THAN 20 ===========`)
// console.log(`===========================================`)
// console.log(`INPUT: [1, 60, 34, 30, 20, 5] |  EXPECTED: [1, 5]  |  OUTPUT:`)
// console.log(filterLessThan20([1, 60, 34, 30, 20, 5]))
// console.log(``)
// console.log(``)
// console.log(`===========================================`)
// console.log(`=========== CALCULATE SUM =================`)
// console.log(`===========================================`)
// console.log(`INPUT:   |  EXPECTED:   |  OUTPUT:`)
// console.log(``)
// console.log(``)
// console.log(``)
// console.log(`===========================================`)
// console.log(`=========== CAPITALIZED PRODUCT ===========`)
// console.log(`===========================================`)
// console.log(`INPUT:   |  EXPECTED:   |  OUTPUT:`)
// console.log(``)
// console.log(``)
// console.log(``)
// console.log(``)
// console.log(``)
// console.log(``)